# guide https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/

name: test_publish

on:
    push:
      branches: [ "dev" ]
    pull_request:
      branches: [ "dev" ]

jobs:
    build-package:
        name: Build distribution
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v3
        - name: Set up Python 3.10
          uses: actions/setup-python@v3
          with:
            python-version: "3.10"
        - name: Install pypa/build
          run: python -m pip install build --user
        - name: build the wheel
          run: python -m build
        - name: Store the distribution package
          uses: actions/upload-artifact@v3
          with:
            name: distribution-package
            path: dist/
    
    publish-to-testpypi:
        name: publish distribution-package to pypi
        # https://stackoverflow.com/questions/18216991/create-a-tag-in-a-github-repository
        needs: build-package
        runs-on: ubuntu-latest
        environment:
            name: testpypi
            url: https://test.pypi.org/p/avicenna
        permissions:
            id-token: write
        steps:
        - name: download dist from build-package job
          uses: actions/download-artifact@v3
          with:
            name: distribution-package
            path: dist/
        - name: Publish distribution-package to pypi
          uses: pypa/gh-action-pypi-publish@release/v1
          with:
            repository-url: https://test.pypi.org/legacy/

#Optional Signing? https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/




